import re
import streamlit as st
from zerogpt_api import check_ai_content


def display_highlighted_text(detection_result):
    data = detection_result.get("data", {})
    ai_segments = data.get("h", [])
    input_text = data.get("input_text", "")
    fake_percentage = data.get("fakePercentage", 0)
    feedback = data.get("feedback", "No feedback provided.")
    is_human = data.get("isHuman", 0)
    ai_words = data.get("aiWords", 0)
    text_words = data.get("textWords", 0)

    # Highlight AI-generated segments
    highlighted_text = input_text
    for term in ai_segments:
        pattern = re.escape(term)
        highlighted_text = re.sub(
            pattern,
            f"<mark style='background-color: yellow; color: black;'>{term}</mark>",
            highlighted_text,
            flags=re.IGNORECASE
        )

    # Initialize session state
    st.session_state.setdefault("show_editor", False)
    st.session_state.setdefault("editable_text", highlighted_text)

    # --- Section Header ---
    #st.markdown("---")
    st.markdown("### 📝 Detected Content")
    # VIEW MODE
    st.markdown(highlighted_text.replace("\n", "<br>"), unsafe_allow_html=True)
    st.markdown(
        """
        <div style="padding:15px;border-radius:10px; background-color:yellow;font-weight: bold;">
            Yellow Highlighted text is generated by AI.
        </div>
        """, unsafe_allow_html=True)
    st.markdown("---")
    st.subheader("🧩 AI Detection Results")

    label = "🧠 AI-Generated" if is_human == 0 else "🧍 Human-Written"
    color = "red" if is_human == 0 else "green"

    st.markdown(
        f"""
        <div style="padding:15px;border-radius:10px;background-color:{"#ffffff" if is_human == 0 else "#071D07"};">
            <h4 style="margin:0;">Prediction: <span style="color:{color};">{label}</span></h4>
            <p style="margin:5px 0;"><b>Feedback:</b> {feedback}</p>
            <p style="margin:5px 0;"><b>AI Probability:</b> {fake_percentage:.2f}%</p>
            <p style="margin:5px 0;"><b>Total Words:</b> {text_words} |
            <b>AI Words:</b> {ai_words} |
            <b>Estimated Human Words:</b> {max(text_words - ai_words, 0)}</p>
        </div>

        """,
        unsafe_allow_html=True,
    )
    # --- Detection Summary (always visible) ---
    # label = "🧠 AI-Generated" if is_human == 0 else "🧍 Human-Written"
    # color = "red" if is_human == 0 else "green"

    # st.markdown(
    #     f"""
    #     <div style="padding:15px;border-radius:10px;background-color:#ffffff;">
    #         <h4 style="margin:0;">Prediction: <span style="color:{color};">{label}</span></h4>
    #         <p style="margin:5px 0;"><b>Feedback:</b> {feedback}</p>
    #         <p style="margin:5px 0;"><b>AI Probability:</b> {fake_percentage:.2f}%</p>
    #         <p style="margin:5px 0;"><b>Total Words:</b> {text_words} |
    #         <b>AI Words:</b> {ai_words} |
    #         <b>Human Words:</b> {max(text_words - ai_words, 0)}</p>
    #     </div>
    #     """,
    #     unsafe_allow_html=True,
    # )
    st.markdown(
        """
        <style>
            .stProgress > div > div > div > div {
                background-color: yellow;
            }

            /* Style for the empty part of the progress bar */
            .stProgress > div > div > div {
                background-color: green;
            }
        </style>""",
        unsafe_allow_html=True
    )
    # st.markdown(
    #     """
    #     <div style="padding:10px; border-radius:10px; background-color:#f5f5f5;">
    #         <span style="background-color:yellow;">AI-Generated Text</span> is highlighted below.
    #     </div>
    #     """,
    #     unsafe_allow_html=True
    # )
    st.progress(min(max(fake_percentage / 100, 0), 1))

    # --- Highlighted / Editable Section ---

    if not st.session_state.show_editor:


        if st.button("✏️ Edit Detected Content"):
            st.session_state.show_editor = True
            st.rerun()

    else:
        # EDIT MODE
        st.markdown("---")
        st.markdown(
            """
            <div style='font-size:22px;'><b style="text-decoration: underline;">Content Editor:</b></div>""",
            unsafe_allow_html=True
        )
        edited_text = st.text_area(
            "",
            value=st.session_state.editable_text.replace(
                "<mark style='background-color: yellow; color: black;'>", ""
            ).replace("</mark>", ""),
            height=400,
        )

        col1, col2 = st.columns(2)
        with col1:
            if st.button("🔁 Recheck with ZeroGPT"):
                with st.spinner("Rechecking edited content..."):
                    new_detection = check_ai_content(edited_text)
                    st.session_state.detection_result = new_detection
                    st.session_state.show_editor = False
                    st.session_state.editable_text = edited_text
                    st.success("✅ Recheck complete!")
                    st.rerun()
        with col2:
            if st.button("❌ Cancel Edit"):
                st.session_state.show_editor = False
                st.rerun()
